### ISSUE TITLE
style and script assets not included

### ISSUE THREAD

**Issue by johnevanofski** [girldevelopit/gdi-core-html-css#24]
Hey there. I wanted to have my GDI Oakland students be able to download this course for offline use, however it appears that the repo does not include the CSS & JS files referenced in the readme. Maybe I'm missing something?

**Comment by johnevanofski** [comment]
Ah, sorry I see it's in the submodule...

**Comment by Roenok** [comment]
Hi @johnevanofski! You weren't the only person with this problem, so you'll be glad to know we removed the submodule in this latest version. Download freely!
