### ISSUE TITLE
Class 3: Slide #16 should use the image from slide #17

### ISSUE THREAD

**Issue by LearningNerd** [girldevelopit/gdi-core-html-css#25]
See the slide here: http://girldevelopit.github.io/gdi-core-html-css/class3.html#/16

It's a little confusing because it talks about padding, but the image highlights the margin instead. Would be better to use the image from http://girldevelopit.github.io/gdi-core-html-css/class3.html#/17

**Comment by Roenok** [comment]
Well spotted! I corrected it. Thanks!
